
name: Run Stock Loser Bot - PM

on:
  schedule:
    - cron: '0 15 * * *'   # 16:00 CET (UTC+1)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script (PM)
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          RUN_TYPE: "PM"
        run: |
          python losers_report.py
