name: Run Stock Loser Bot

on:
  schedule:
    - cron: '0 11 * * *'   # 12 PM CET (CET = UTC+1, adjust for daylight savings)
    - cron: '0 15 * * *'   # 4 PM CET
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  --no-cache-dir -r requirements.txt
      
       #🔍 Debug your secrets
      - name: Debug secrets
        run: |
          echo "SMTP_USER: ${{ secrets.EMAIL_USER }}"
          echo "SMTP_PASS length: ${#SMTP_PASS}"
        env:
          SMTP_PASS: ${{ secrets.EMAIL_PASS }}

      # 🔍 Test Gmail login
      - name: Test Gmail login
        run: |
          python - <<EOF
          import smtplib, os
          user = os.environ.get("SMTP_USER")
          pw = os.environ.get("SMTP_PASS")
          try:
              with smtplib.SMTP("smtp.gmail.com", 587) as s:
                  s.starttls()
                  s.login(user, pw)
                  print("✅ Gmail login success")
          except Exception as e:
              print("❌ Gmail login failed:", e)
          EOF
      
      - name: Run script
        env:
         FROM_EMAIL: ${{ secrets.EMAIL_USER }}
         #SMTP_USER: ${{ secrets.EMAIL_USER }}
         SMTP_PASS: ${{ secrets.EMAIL_PASS }}
         TO_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        run: |
          python losers_report.py  || true

